apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: asm-multicluster-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # Use Istio's ingress gateway deployed by ASM
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
