apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 12
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: southamerica-west1-docker.pkg.dev/dryruns/dr-testing/dr-testing:latest
        env:
        - name: GKE_REGION
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_REGION
          valueFrom:
            resourceFieldRef:
              containerName: nodejs-app
              resource: requests.cpu
              divisor: 1
        ports:
        - containerPort: 8080
      restartPolicy: Set
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080